<?php
$b64 = "MIIJZjCCB06gAwIBAgIINwWEx4xFrSEwDQYJKoZIhvcNAQELBQAwgbgxCzAJBgNVBAYTAkVTMUQw
QgYDVQQHDDtCYXJjZWxvbmEgKHNlZSBjdXJyZW50IGFkZHJlc3MgYXQgd3d3LnVhbmF0YWNhLmNv
bS9hZGRyZXNzKTEWMBQGA1UECgwNVUFOQVRBQ0EgUy5BLjEVMBMGA1UECwwMVFNQLVVBTkFUQUNB
MRowGAYDVQQDDBFVQU5BVEFDQSBDQTIgMjAxNjEYMBYGA1UEYQwPVkFURVMtQTY2NzIxNDk5MB4X
DTI1MDQwNDE2NTcwMFoXDTI3MDQwNDE2NTcwMFowgaQxCzAJBgNVBAYTAkVDMRkwFwYDVQQEDBBB
TE1FSURBIFpBTUJSQU5PMRcwFQYDVQQqDA5FRElTT04gRVJORVNUTzEZMBcGA1UEBRMQSURDRUMt
MTMxMDY3NTM0MTEoMCYGA1UEAwwfRURJU09OIEVSTkVTVE8gQUxNRUlEQSBaQU1CUkFOTzEcMBoG
A1UEYQwTVElORUMtMTMxMDY3NTM0MTAwMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AL275qwR3y9AFQxEVXDqQCCLT2XON1UxGTN/l2PJaEY6+XmIxQP1PEFe5JzfYAvZAajKD1W/Hmnv
EttM62Vfhm730mXCesmH3kV++tqIKV13tQ1S26sX0GQOAfO3zZOTP1BXTHEimWjk7u3v5+05fUzG
YPuOA1b4GVgbz8i3e80bpMv8bY8hg9uG1BndCKNWshbS10DJSJ7DHGr02xnn+Eef6FPluP443UaZ
+QN+QAwytvj/yYkoxplO6Tjn3nCC/hcrzhMnoX/w1HRuz7IoCBp1c5KUbmOVSftCRReerTYKhiFk
boiNnNiCg2N0rLFdoxMXr3z8SYpXRvre9yw9zv0CAwEAAaOCBIQwggSAMBsGCysGAQQBgvE2ZgMB
BAwMCjEzMTA2NzUzNDEwHgYLKwYBBAGC8TZmAwsEDwwNMTMxMDY3NTM0MTAwMTCB1wYIKwYBBQUH
AQEEgcowgccwVQYIKwYBBQUHMAKGSWh0dHA6Ly93d3cudWFuYXRhY2EuY29tL3B1YmxpYy9kb3du
bG9hZC90c3BfY2VydGlmaWNhdGVzL3N1Ym9yZGluYXRlMS5jcnQwNgYIKwYBBQUHMAGGKmh0dHA6
Ly9vY3NwMS51YW5hdGFjYS5jb20vcHVibGljL3BraS9vY3NwLzA2BggrBgEFBQcwAYYqaHR0cDov
L29jc3AyLnVhbmF0YWNhLmNvbS9wdWJsaWMvcGtpL29jc3AvMB0GA1UdDgQWBBSb8flp7lCOR/Di
xvZzqUyQ+TDGDDAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFH1X52BzzgdGqeKjaPDhEbJ0knP9
MIGZBgNVHSAEgZEwgY4wgYsGDCsGAQQBgvE2ZgIBATB7MDcGCCsGAQUFBwIBFitodHRwczovL3d3
dy51YW5hdGFjYS5jb20vcHVibGljL3BraS9kcGMtZWMvMEAGCCsGAQUFBwICMDQMMkNFUlRJRklD
QURPIERFIFBFUlNPTkEgTkFUVVJBTCBPIEZJU0lDQSBFTiBBUkNISVZPMIGPBgNVHR8EgYcwgYQw
QKA+oDyGOmh0dHA6Ly9jcmwxLnVhbmF0YWNhLmNvbS9wdWJsaWMvcGtpL2NybC9DQTJzdWJvcmRp
bmFkYS5jcmwwQKA+oDyGOmh0dHA6Ly9jcmwyLnVhbmF0YWNhLmNvbS9wdWJsaWMvcGtpL2NybC9D
QTJzdWJvcmRpbmFkYS5jcmwwDgYDVR0PAQH/BAQDAgXgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
BgEFBQcDBDCCAboGA1UdEQSCAbEwggGtgRNkbnRlc2l0ZWNAZ21haWwuY29toBsGCysGAQQBgvE2
ZgMBoAwMCjEzMTA2NzUzNDGgHwYLKwYBBAGC8TZmAwKgEAwORURJU09OIEVSTkVTVE+gGAYLKwYB
BAGC8TZmAwOgCQwHQUxNRUlEQaAZBgsrBgEEAYLxNmYDBKAKDAhaQU1CUkFOT6BwBgsrBgEEAYLx
NmYDB6BhDF9DQUxMRTogIEFWLiBFTE9ZIEFMRkFSTyAgTk1FUk86ICBTIE4gIFJFRkVSRU5DSUE6
ICBBIFRSRUlOVEEgTUVUUk9TIERFTCBDT0xFR0lPIFJBWU1VTkRPIEFWRUlHQaAfBgsrBgEEAYLx
NmYDCKAQDA4wMDU5Mzk4Nzk4MzY2MaAWBgsrBgEEAYLxNmYDCaAHDAVDSE9ORaAeBgsrBgEEAYLx
NmYDC6APDA0xMzEwNjc1MzQxMDAxoBMGCysGAQQBgvE2ZgMMoAQMAkVDoCkGCysGAQQBgvE2ZgMy
oBoMGFBFUlNPTkEgTkFUVVJBTCBPIEZJU0lDQaAYBgsrBgEEAYLxNmYDM6AJDAdBUkNISVZPMA0G
CSqGSIb3DQEBCwUAA4ICAQBunrt+D3WVIo81iiyz/Ziq22GJUId5r8A+Ic2qK1lU8mjSyqpafyij
9oEqkg+9fXpf8r2jK6+3N5x7S7sFvtevffDP9Nlo3vgSfi5Vk4wsWipaZzkuki0bt7qOu5y4+GkO
legsxRso86yCj5vmne5bjsHdoyLa92YPmHIUmBLQQbe+WErjKq40RFGU7J0woQjyV7mA9lWphKQA
cLw3pIMEYWoLh+YVAVvs9M/4sWZoGx4Nh2YInTQCpOvTSVg9Z6oqP/z9U9NOuX49GcL8QeY/F9tK
f/EBj1dsWr7fQ5kSzxm4hAGxs/p58GOoFS+E/Ny+YG8kqogSoedh44Z9K6o2HRF86pAy2JZH/Tmf
+bqqKjrhm6hhsHTJ9AFlr/UB+BSyN9ZVQ6bQbtm3xoemV01XInYhYOfjt64gSThA4xW4ioKU77u7
o8yEwQ2yR9nHYU4b2/TPaKc60pTC3vqxRM/fU460TBGABx3CxuutSta+1h8VCKo9PBJ0Gu0jhZSm
y93E7z8wHOUEc9VDzf6glhpuheAsUu+OoGQZoX4M76Sif0YunpwqxhBDqgAt/7Wc6ZB6tWsJUWF9
GSalZ7QqCCqx9q97yzmqmg23DOi3ytLmsg+4mYASOeGfOXCBPhSoC1U6bYeQiOohSICPwzcyrRZl
L30d88rSZNU6ev4NGIiZDQ==";

$pem = "-----BEGIN CERTIFICATE-----\n" . $b64 . "\n-----END CERTIFICATE-----\n";
$certData = openssl_x509_parse($pem);

function buildIssuerName(array $certData): string
{
    $issuer = [];
    $issuerMap = $certData['issuer'];
    
    // Reverse the array to match RFC2253 / Java X500Principal format
    $keys = array_reverse(array_keys($issuerMap));
    
    foreach ($keys as $key) {
        $value = $issuerMap[$key];
        if (is_array($value)) {
            $value = $value[0];
        }
        
        if ($key === 'organizationIdentifier' || $key === '2.5.4.97') {
            $key = '2.5.4.97';
            // RFC2253 expects '#' + hex encoding of the DER encoded value for unknown OIDs
            // Tag 0x0C = UTF8String
            $hex = '0c' . sprintf('%02x', strlen($value)) . bin2hex($value);
            $value = '#' . $hex;
        }
        
        $issuer[] = $key . '=' . $value;
    }
    return implode(',', $issuer);
}

echo "Result:\n" . buildIssuerName($certData) . "\n";
