<?php

namespace App\Enums;

enum TipoMovimientoInventario: string
{
    case MOV_01_INVENTARIO_INICIAL = 'MOV_01_INVENTARIO_INICIAL';
    case MOV_02_COMPRA = 'MOV_02_COMPRA';
    case MOV_03_VENTA_INMEDIATA = 'MOV_03_VENTA_INMEDIATA';
    case MOV_04_RESERVA_DESPACHO = 'MOV_04_RESERVA_DESPACHO';
    case MOV_05_ENTREGA_DESPACHO = 'MOV_05_ENTREGA_DESPACHO';
    case MOV_06_TRANSFERENCIA_INTERNA = 'MOV_06_TRANSFERENCIA_INTERNA';
    case MOV_07_TRANSFERENCIA_SUCURSALES = 'MOV_07_TRANSFERENCIA_SUCURSALES';
    case MOV_08_RECEPCION_TRANSFERENCIA = 'MOV_08_RECEPCION_TRANSFERENCIA';
    case MOV_09_AJUSTE_POSITIVO = 'MOV_09_AJUSTE_POSITIVO';
    case MOV_10_AJUSTE_NEGATIVO = 'MOV_10_AJUSTE_NEGATIVO';
    case MOV_11_ENVIO_MERMAS = 'MOV_11_ENVIO_MERMAS';
    case MOV_12_REACONDICIONAMIENTO_MERMAS = 'MOV_12_REACONDICIONAMIENTO_MERMAS';
    case MOV_13_ENTRADA_ANULACION_COMPROBANTE = 'MOV_13_ENTRADA_ANULACION_COMPROBANTE';
    case MOV_14_ENTRADA_ANULACION_OPERATIVA = 'MOV_14_ENTRADA_ANULACION_OPERATIVA';
    case MOV_15_ENTRADA_CORRECCION_NC = 'MOV_15_ENTRADA_CORRECCION_NC';
    case MOV_16_ENTRADA_CORRECCION_EDICION = 'MOV_16_ENTRADA_CORRECCION_EDICION';
    case MOV_17_DEVOLUCION_PROVEEDOR = 'MOV_17_DEVOLUCION_PROVEEDOR';
    case MOV_18_ENTRADA_DEVOLUCION_PARCIAL_NC = 'MOV_18_ENTRADA_DEVOLUCION_PARCIAL_NC';
    case MOV_19_ENTRADA_DEVOLUCION_COMPLETA_NC = 'MOV_19_ENTRADA_DEVOLUCION_COMPLETA_NC';
    case MOV_20_ENTRADA_DEVOLUCION_COMPLETA_ANULACION = 'MOV_20_ENTRADA_DEVOLUCION_COMPLETA_ANULACION';
}
